
![](https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/NumPy_logo_2020.svg/330px-NumPy_logo_2020.svg.png)

# 01. 넘파이 기초

학습 목표

- Numpy 배열의 기본 개념을 이해합니다.
- 1차원, 2차원, 3차원 배열을 만들 수 있습니다.
- Reshape 기능을 사용해 배열 형태를 바꿀 수 있습니다.
- 인덱싱과 슬라이싱으로 원하는 데이터를 조회할 수 있습니다.
- 배열 사이의 기본적인 연산을 수행할 수 있습니다.

## 1.라이브러리 불러오기

- Numpy 배열을 사용하려면 우선 **numpy** 라이브러리를 불러와야 합니다.
- numpy 라이브러리는 일반적으로 **np** 별칭을 붙여 불러옵니다.

In [ ]:
# 라이브러리 불러오기
import numpy as np

## 2.배열 만들기

- 편의를 위해 **Numpy 배열**을 그냥 **배열**이라고 부르기로 합시다.
- 이후 데이터 처리시 배열로 변환해 연산을 하거나, 결과가 배열로 표시되는 경우가 있습니다.
- 배열에 대한 개념은 정확히 파악해 두기를 권고합니다.

### (1) 용어 정의

<img src='https://raw.githubusercontent.com/Jangrae/img/master/array.png' width=300 align="left"/>

**[용어]**
- axis: 배열의 각 축
- rank: 축의 개수
- shape: 축의 길이, 배열의 크기

  
**[3 x 4 배열의 경우]**
- axis 0 과 axis 1 을 갖는 2차원 배열
- rank 2 array 
- shape는 (3, 4)

### (2) 배열 만들기

- **np.array() 함수**를 사용해서 배열을 만듭니다.
- 대부분 **리스트**로부터 배열을 만들거나, 머신러닝 관련 함수 결괏값이 배열이 됩니다.

#### 1) 배열 만들기

**1) 1차원 배열 만들기**

In [ ]:
# 1차원 리스트
a1 = [1, 2, 3, 4, 5]

# 배열로 변환
b1 = np.array(a1)

# 확인
print(b1)

**2) 2차원 배열 만들기**

In [ ]:
# 2차원 리스트 
# a2 = [[1.5, 2.5, 3.2], [4.2, 5.7, 6.4]]
a2 = [[1.5, 2.5, 3.2], 
      [4.2, 5.7, 6.4]]

# 배열로 변환
b2 = np.array(a2)

# 확인
print(b2)

**3) 3차원 배열 만들기**

In [ ]:
# 3차원 리스트
# a3 = [[[1, 3, 1], [4, 7, 6], [8, 3, 4]], [[6, 2, 4], [8, 1, 5], [3, 5, 9]]]
a3 = [[[1, 3, 1],
       [4, 7, 6],
       [8, 3, 4]],
      [[6, 2, 4],  
       [8, 1, 5],
       [3, 5, 9]]]

# 배열로 변환
b3 = np.array(a3)

# 확인
print(b3)

#### 2) 배열 정보 확인

- 배열 정보를 확인하는 다음 속성들을 기억하시기 바랍니다.
- 특히 shape 속성은 이후에도 많이 사용될 것입니다.

<img src='https://github.com/DA4BAM/image/blob/main/1,2,3%20%EC%B0%A8%EC%9B%90.png?raw=true' width=800 align="left"/>

**1) 차원 확인**

- ndim 속성으로 배열 차원을 확인합니다.

In [ ]:
# 차원 확인
print(b1.ndim)
print(b2.ndim)
print(b3.ndim)

**2) 형태(크기) 확인**

- shape 속성으로 배열 형태를 확인합니다.
- 결과는 다음과 같은 형태의 튜플로 표시됩니다.
    - 1차원: (x, )
    - 2차원: (x, y)
    - 3차원: (x, y, z)
- 앞에서 부터 axis 0, axis 1, axis 2의 크기를 의미합니다.

In [ ]:
# 형태(크기) 확인
print(b1.shape) 
print(b2.shape) 
print(b3.shape) 

**3) 요소 자료형 확인**

- dtype 속성으로 배열에 포함된 요소들의 자료형을 확인합니다.
- 배열은 한 가지 자료형만 가질 수 있다는 특징이 있습니다.

In [ ]:
# 요소 자료형 형식 확인
print(b1.dtype)
print(b2.dtype)
print(b3.dtype)

<img src='https://raw.githubusercontent.com/jangrae/img/master/practice_01.png' width=120 align="left"/>

[문1] numpy 라이브러리를 np 별칭을 주어 불러오세요.

In [ ]:
# 라이브러리 불러오기
import numpy as np

[문2] 다음에 주어진 데이터를 갖는 1차원 배열을 만든 후 ndim, shape, dtype을 확인해 보세요.

In [ ]:
# 10, 11, 12, 13, 14, 15

# 배열 만들기
arr = np.array([10, 11, 12, 13, 14, 15])

# 확인
print(arr)

# 정보 확인
print(arr.ndim)
print(arr.shape)
print(arr.dtype)

[문3] 다음에 주어진 리스트를 요소로 갖는 2차원 배열을 만든 후 ndim, shape, dtype을 확인해 보세요

In [ ]:
a = [[11, 12, 13, 14], [15, 16, 17, 18], [19, 20, 21, 22]]

# 배열 만들기
arr = np.array(a)

# 확인
print(arr)

# 정보 확인
print(arr.ndim)
print(arr.shape)
print(arr.dtype)

#### 2) Reshape

- 배열을 사용할 때 다양한 형태(Shape)로 변환할 필요가 있습니다.
- 배열에 포함된 **요소가 사라지지 않는 형태**라면 자유롭게 변환할 수 있습니다.
- (3, 4) → (2, 6) → (4, 3) → (12, 1) → (6, 2) 등등 요소 개수만 변하지 않으면 됩니다.

In [ ]:
# (2, 3) 형태의 2차원 배열 만들기
a = np.array([[1, 2, 3], 
              [4, 5, 6]])

# 확인
print(a)

**1) (2, 3) → (3, 2)**

In [ ]:
# (3, 2) 형태의 2차원 배열로 Reshape
b = a.reshape(3, 2)

# 확인
print(b)

**2) (2, 3) → (6,)**

In [ ]:
# 1차원 배열로 Reshape
# c = a.reshape(6,)
c = a.reshape(6)

# 확인
print(c)

**3) -1의 편리성**

- **(*m*, -1)** 또는 **(-1, *n*)** 처럼 사용해 행 또는 열 크기 한 쪽만 지정할 수 있습니다.

In [ ]:
# (2, 3) 형태의 2차원 배열 만들기
a = np.array([[1, 2, 3], 
              [4, 5, 6]])

# 확인
print(a)

In [ ]:
# reshape(m, -1) 형태로 지정하여 Reshape 가능
print(a.reshape(1, -1))
print()

print(a.reshape(2, -1))
print()

print(a.reshape(3, -1))
print()

#print(a.reshape(4, -1))
#print(a.reshape(5, -1))

print(a.reshape(6, -1))

<img src='https://raw.githubusercontent.com/jangrae/img/master/practice_01.png' width=120 align="left"/>

[문1] 다음에 주어진 배열의 형태(shape)를 확인한 후 요구되는 형태로 바꿔 보세요.

In [ ]:
# 배열 만들기
a = np.array([[11, 12, 13, 14], 
              [15, 16, 17, 18], 
              [19, 20, 21, 22]])

# 배열 형태 확인
print(a.shape)

# (4, ?))형태의 2차원 배열
a1 = a.reshape(4, -1)

# 확인
print(a1)

# (2, ?) 형태의 2차원 배열
a2 = a.reshape(2, -1)

# 확인
print(a2)

## 3.배열 인덱싱과 슬라이싱

- 지금까지 다룬 자료형들 보다 배열 인덱싱과 슬라이싱이 조금 어렵습니다.

### (1) 인덱싱

- 1차원 배열은 리스트와 방법이 같으므로 설명을 생략합니다.
- **배열[행, 열]** 형태로 특정 위치의 요소를 조회합니다.
- **배열[[행1,행2,..], :]** 또는 **배열[[행1,행2,..]]** 형태로 특정 행을 조회합니다.
- **배열[:, [열1,열2,...]]** 형태로 특정 열을 조회합니다.
- **배열[[행1,행2,...], [열1,열2,...]]** 형태로 특정 행의 특정 열을 조회합니다.

<img src='https://github.com/DA4BAM/image/blob/main/%EB%B0%B0%EC%97%B4%20%EC%8A%AC%EB%9D%BC%EC%9D%B4%EC%8B%B1.png?raw=true' width=800 align="left"/>

In [ ]:
# (3, 3) 형태의 2차원 배열 만들기
a = np.array([[1, 2, 3],
              [4, 5, 6], 
              [7, 8, 9]])

# 확인
print(a)             

**1) 요소 조회**

In [ ]:
# 첫 번째 행, 두 번째 열 요소 조회
print(a[0, 1])

**2) 행 조회**

In [ ]:
# 첫 번째, 두 번째 행 조회
# print(a[[0, 1], :])
print(a[[0, 1]])

In [ ]:
# 첫 번째, 두 번째, 세 번째 행 조회
# print(a[[0, 1, 2], :])
print(a[[0, 1, 2]])

**3) 열 조회**

In [ ]:
# 첫 번째, 두 번째 열 조회
print(a[:, [0, 1]])

**4) 행, 열 조회**

In [ ]:
# 배열 확인
print(a)

In [ ]:
# 두 번째 행 두 번째 열의 요소 조회
print(a[[1], [1]])

In [ ]:
# 세 번째 행 두 번째 열의 요소 조회
print(a[[2], [1]])

<img src='https://raw.githubusercontent.com/jangrae/img/master/practice_01.png' width=120 align="left"/>

주어진 배열을 이용하여 다음 결과를 얻도록 문제를 푸시오.

In [ ]:
a = np.array([[11, 12, 13, 14], 
              [15, 16, 17, 18], 
              [19, 20, 21, 22]])

[문1] 16

In [ ]:
a[1,1]

[문2] [19 20 21 22]

In [ ]:
a[2]

[문3] [13  17  21]

In [ ]:
a[:,2]

### (2) 슬라이싱

- **배열[행1:행N,열1:열N]** 형태로 지정해 그 위치의 요소를 조회합니다.
- 조회 결과는 **2차원 배열**이 됩니다.
- 마지막 **범위 값은 대상에 포함되지 않습니다.**
- 즉, **배열[1:M, 2:N]**이라면 1 ~ M-1행, 2 ~ N-1열이 조회 대상이 됩니다.

<img src='https://github.com/DA4BAM/image/blob/main/%EB%B0%B0%EC%97%B4%20%EC%8A%AC%EB%9D%BC%EC%9D%B4%EC%8B%B12.png?raw=true' width=800 align="left"/>

In [ ]:
# (3, 3) 형태의 2차원 배열 만들기
a = np.array([[1, 2, 3],
              [4, 5, 6], 
              [7, 8, 9]])

# 확인
print(a)             

In [ ]:
# 첫 번째 ~ 두 번째 행 조회
# print(a[0:2, :])
print(a[0:2])

In [ ]:
# 첫 번째 행, 첫 번째 ~ 두 번째 열 조회
print(a[0, 0:2])

In [ ]:
# 첫 번째 ~ 세 번째 행, 두 번째 ~ 세 번째 열 조회
print(a[0:3, 1:3])

In [ ]:
# 두 번째 ~ 끝 행, 두 번째 ~ 끝 열 조회
print(a[1:, 1:])

<img src='https://raw.githubusercontent.com/jangrae/img/master/practice_01.png' width=120 align="left"/>

주어진 배열을 이용하여 다음 결과를 얻도록 문제를 푸시오.

In [ ]:
a = np.array([[11, 12, 13, 14], 
              [15, 16, 17, 18], 
              [19, 20, 21, 22]])

In [ ]:
a[1:2,0:1]

[문1]   

[[12  
16  
20]

In [ ]:
a[:,1:2]

[문2] 

[[16  17  
 20  21]]

In [ ]:
a[1:, 1:3]

### (3) 조건 조회

- **조건에 맞는 요소를 선택**하는 방식이며, **불리안 방식**이라고 부릅니다.
- 조회 결과는 **1차원 배열**이 됩니다.

In [ ]:
# 2차원 배열 만들기
score= np.array([[78, 91, 84, 89, 93, 65],
                 [82, 87, 96, 79, 91, 73]])

# 확인
print(score)

- **배열[조건]** 형태로 해당 조건에 맞는 요소만 조회합니다.

In [ ]:
# 요소 중에서 90 이상인 것만 조회
print(score[score >= 90])

- 검색 조건을 변수로 선언해 사용할 수 있습니다.

In [ ]:
# 요소 중에서 90 이상인 것만 조회
condition = score >= 90
print(score[condition])

- 여러 조건을 **&** 와 **|** 로 연결하여 조회할 수 있습니다.

In [ ]:
# 모든 요소 중에서 90 이상 95 미만인 것만 조회
print(score[(score >= 90) & (score <= 95)])

<img src='https://raw.githubusercontent.com/jangrae/img/master/practice_01.png' width=120 align = "left"/>

[문1] 다음 배열에서 80 미만의 데이터만 추출하시오.

In [ ]:
# 2차원 배열 만들기
score= np.array([[78, 91, 84, 89, 93, 65],
                 [82, 87, 96, 79, 91, 73]])

# 확인
print(score)

# 짝수만 조회
print(score[score <80 ])

[문2] 다음 배열에서 짝수만 추출해 보세요.

In [ ]:
# 2차원 배열 만들기
score= np.array([[78, 91, 84, 89, 93, 65],
                 [82, 87, 96, 79, 91, 73]])

# 확인
print(score)

# 짝수만 조회
print(score[score % 2 == 0])

## 4.배열 연산

- 배열 사이의 더하기, 빼기, 곱하기, 나누기 등은 이해하기 쉽습니다.
- 하지만 행렬 곱, 행렬 합등의 연산은 악갼의 수학적 지식이 필요합니다.
- 행렬 연산은 선형 대수를 위한 것이므로 설명을 생략합니다.

<img src='https://github.com/DA4BAM/image/blob/main/%EB%B0%B0%EC%97%B4%EC%97%B0%EC%82%B0.png?raw=true' width=600 align="left"/>

In [ ]:
# 두 개의 (2, 2) 형태의 2차원 배열 만들기
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])

# 확인
print(x)
print(y)

**1) 배열 더하기**

- \+ 또는 **np.add()** 함수를 사용합니다.

In [ ]:
# 배열 더하기
print(x + y)

# 또는
print(np.add(x, y))

**2) 배열 뺴기**

- \- 또는 **np.subtract()** 함수를 사용합니다.

In [ ]:
# 배열 빼기
print(x - y)

# 또는
print(np.subtract(x, y))

**3) 배열 곱하기**

- \* 또는 **np.multiply()** 함수를 사용합니다.

In [ ]:
# 배열 곱하기
print(x * y)

# 또는
print(np.multiply(x, y))

**4) 배열 나누기**

- \/ 또는 **np.divide()** 함수를 사용합니다.

In [ ]:
# 배열 나누기
print(x / y)

# 또는
print(np.divide(x, y))

**5) 배열 제곱**

- \** 또는 **np.power()** 함수를 사용합니다.

In [ ]:
# 배열 y 제곱
print(x ** y)

# 또는
print(np.power(x, y))

In [ ]:
# 배열 제곱
print(x ** 2)

**6) 배열 집계**

- np.sum(), 혹은 array.sum()
    * axis = 0 : 열 기준 집계
    * axis = 1 : 행 기준 집계
    * 생략하면 : 전체 집계
- 동일한 형태로 사용 가능한 함수 : np.max(), np.min, np.mean(), np.std()

In [ ]:
# array를 생성합니다.
a = np.array([[1,5,7],[2,3,8]])
print(a)

In [ ]:
# 전체 집계
print(np.sum(a))

# 열기준 집계
print(np.sum(a, axis = 0))

# 행기준 집계
print(np.sum(a, axis = 1))

* 추가로, np.argmax(), np.argmin() 도 있습니다. 

<img src='https://github.com/DA4BAM/image/blob/main/%EB%B0%B0%EC%97%B4_argmin.png?raw=true' width=800 align="left"/>

In [ ]:
print(a)
# 전체 중에서 가장 큰 값의 인덱스
print(np.argmax(a))

# 행 방향 최대값의 인덱스
print(np.argmax(a, axis = 0))

# 열 방향 최대값의 인덱스
print(np.argmax(a, axis = 1))


## 5.복습문제

1) numpy 라이브러리를 np 별칭을 주어 불러오세요.

In [ ]:
# 라이브러리 불러오기
import numpy as np

2) 다음 형태를 갖는 2차원 배열을 만들어 np_arr 변수로 선언하세요.

In [ ]:
# [[  1  2  3]
#  [  4  5  6]
#  [  7  8  9]
#  [ 10 11 12]]

# 배열 만들기
np_arr = np.array([[  1,  2,  3],
                   [  4,  5,  6],
                   [  7,  8,  9],
                   [ 10, 11, 12]])

# 확인
print(np_arr)

3) shape 속성을 사용해 np_arr 배열의 행과 열의 크기를 확인하세요.

In [ ]:
# 배열 크기 확인
np_arr.shape

4) np_arr 배열을 아래 주어진 3 X 4 형태의 배열로 바꿔서 np_02 배열로 선언하고 확인하세요.

In [ ]:
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]

# 형태 변경
np_02 = np_arr.reshape(3, -1)

# 확인
print(np_02)

5) np_arr 배열의 세 번째 행의 요소들을 조회하세요.

In [ ]:
# [7 8 9] 조회
print(np_arr[2])

6) np_arr 배열의 모든 요소에 10을 곱한 결과를 조회하세요.

In [ ]:
# 10 곱하기
print(np_arr * 10)

7) 아래의 출력문이 어떤 값을 출력할 지 추측한 후에 결과를 확인하세요.  
[ 8  9 10 11 12]

In [ ]:
# 조건 조회
print(np_arr[np_arr > 7])

8) 7번 실습에서 선택된 요소들의 값만 각각 2배로 만드세요.

In [ ]:
# 조회 결과에 대한 연산
np_arr[np_arr > 7] = np_arr[np_arr > 7] * 2

9) np_arr 배열의 값을 조회해서 변경된 내용을 확인해 보세요.

In [ ]:
# 원본 배열 확인
print(np_arr)

10) np_arr 배열의 요소들 중에서 3의 배수는 1, 아니면 0인 배열을 만들고 조회하시오.

In [ ]:
a = np.where(np_arr % 2 == 0, 0, 1)
print(a)

11) np_arr의 전체 평균, 열별 평균, 행별 평균을 구하세요.

In [ ]:
print(np_arr)
print('-'* 50)
print(np.mean(np_arr))
print('-'* 50)
print(np.mean(np_arr, axis = 0))
print('-'* 50)
print(np.mean(np_arr, axis = 1))